program: src/exam_project/train.py
method: bayes
metric:
  goal: minimize
  name: validation_loss
parameters:
  models.lr:
    min: 0.0001
    max: 0.01
    distribution: log_uniform_values
  models.dropout:
    values: [0.1, 0.3, 0.5]
  # models.hidden:
  #   values:
  #     - "[128, 256]"
  models:
    value: ann
  trainer.max_epochs:
    values: [10, 15, 20]
  trainer.limit_train_batches:
    value: 0.05
  trainer.limit_val_batches:
    value: 0.05

early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
command: # Indicates that wandb agent should run this code. 
  - ${env} # Handles environment variables like WANDB_API_KEY
  - python # Calls python
  - ${program} # Calls the path at the top
  - ${args_no_hyphens} # Ensures that hydra notation is used. 

# As an example it would look something like this:
# python src/exam_project/train.py models.lr=0.0001 models.dropout=0.1 ...
# If ${args_no_hyphens}: python src/exam_project/train.py --models.lr=0.0001 --models.dropout=0.1 ...
# Which would crash hydra