paths:
  data_processed: 'processed'
  data_raw: 'raw/datasets/msambare/fer2013/versions/1/'
  data_root: 'data'
  data_version_path: '1'
  kaggle_id: 'msambare/fer2013'
  processed_str: 'processed'
  raw_str: 'raw'
  train_images: 'train_images.pt'
  train_target: 'train_target.pt'
  val_images: 'val_images.pt'
  val_target: 'val_target.pt'
  test_images: 'test_images.pt'
  test_target: 'test_target.pt'

hyperparameters:
  batch_size: 128
  learning_rate: 1e-3
  seed: 42
  trainvalsplit: 0.8

# configurations for BaseCNN model class
models:
  basecnn:
    _target_: model.BaseCNN
    img_size: 48
    output_dim: 7
    lr: 1e-3
    dropout: 0.6
  baseann:
    _target_: model.BaseANN
    img_size: 48
    output_dim: 7
    hidden: (512, 256)
    dropout: 0.3
    lr: 1e-3
  vitclf:
    _target_: model.ViTClassifier
    model_name: "google/vit-base-patch16-224-in21k"
    lr: 1e-4
    freeze_backbone: True
    output_dim: 7


optimizer:
  _target_: test.Optimizer
  algo: SGD
  lr: 0.01







