defaults:
  - _self_
  - debug: default

paths:
  data_root: 'data'
  data_version_path: '1'
  kaggle_id: 'msambare/fer2013'
  processed_str: 'processed'
  raw_str: 'raw'

hyperparameters:
  seed: 42
  trainvalsplit: 0.8

meta:
  expected_classes: ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]
  expected_mode: "L"
  img_size: 48